import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { presetName, svgCode } = await request.json();

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured on the server." },
        { status: 500 }
      );
    }

    const systemPrompt = `You are an expert SEO contributor for stock video marketplaces (such as Adobe Stock, Shutterstock, and Pond5).
Analyze the following details of an animated SVG template:
Preset Name: ${presetName || "Custom SVG"}
SVG Code Content:
${svgCode || ""}

Based on this:
1. Generate a search-optimized title (maximum 70 characters) that describes the visual movement, colors, mood, and subject of the animation. Do not use generic titles.
2. Generate 40 highly relevant, high-converting tags/keywords separated by commas. Focus on visual description, style (e.g. abstract, flat, neon, HUD), format, motion, and usage.

You MUST respond with a single valid JSON object containing exactly these two keys: "title" and "keywords".
Example JSON Response:
{
  "title": "Abstract Cyberpunk Grid Matrix Loop, Glowing Neon Motion Graphics",
  "keywords": "cyberpunk, hud, neon, portal, technology, loop, abstract, virtual reality, sci-fi"
}

Do not wrap your response in markdown code blocks like \`\`\`json. Return ONLY the raw JSON string.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: systemPrompt,
                },
              ],
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      return NextResponse.json(
        { error: `Gemini API returned error: ${errorText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      return NextResponse.json(
        { error: "No response text generated by Gemini." },
        { status: 500 }
      );
    }

    // Clean up any markdown helper wrappers if the LLM returned it
    let cleanText = generatedText.trim();
    if (cleanText.startsWith("```")) {
      cleanText = cleanText.replace(/^```json\s*/i, "").replace(/```$/, "").trim();
    }

    const result = JSON.parse(cleanText);
    return NextResponse.json(result);
  } catch (error: any) {
    console.error("Error in metadata generation route:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate metadata." },
      { status: 500 }
    );
  }
}
