import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { presetName, svgCode } = await request.json();

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error("[API Error] GEMINI_API_KEY is missing from process.env. Keys available:", Object.keys(process.env));
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured on the server." },
        { status: 500 }
      );
    }

    const systemPrompt = `You are an expert Adobe Stock Video Metadata and Search Optimization Specialist.
Analyze the following details of an animated SVG template:
Preset Name: ${presetName || "Custom SVG"}
SVG Code Content:
${svgCode || ""}

Your task is to analyze the details carefully and generate accurate, commercially useful, highly searchable Adobe Stock metadata.
The goal is to generate the MOST ACCURATE, RELEVANT and SEARCHABLE metadata based ONLY on what is actually visible and clearly supported by the video.

STEP 1 — ANALYZE THE VISUALS
Identify:
1. Asset type: stock footage, animation, motion graphic, abstract animation, vector animation, background, overlay, icon/logo animation.
2. Motion characteristics and important visual elements (e.g., rotating, pulsing, flowing, looping).
3. Composition, background, and visual style (e.g., minimal, flat vector, neon, glowing).

STEP 2 — TITLE GENERATION
Generate ONE concise, factual, buyer-friendly title.
Maximum length: 70 characters.
- Put the main subject near the beginning.
- Describe the visual movement, colors, and subject of the animation.
- Do NOT use generic adjectives like "amazing", "beautiful", "stunning", "masterpiece".
- Avoid brands, trademarks, or unsupported concepts.

STEP 3 — KEYWORD GENERATION
Generate exactly 40 unique, highly relevant keywords separated by commas.
Rank keywords from MOST IMPORTANT to LEAST IMPORTANT. The first 10 keywords are the highest priority.
Tiers to include:
- Primary search terms (subject, action).
- Specific visual characteristics (colors, shapes, objects, lighting).
- Motion and animation terms (rotating, flowing, glowing, looping, seamless loop).
- Background and composition (isolated, minimal, black background, white background).
- Style and visual category (motion graphics, vector animation, abstract animation, neon).
- Conceptual keywords (technology, loading, energy) only when strongly supported.

Do not use "loop" or "seamless loop" unless the SVG code shows looping animations.
Do not use "transparent background" or "alpha channel" unless the SVG background is transparent.

You MUST respond with a single valid JSON object containing exactly these two keys: "title" and "keywords".
Example JSON Response:
{
  "title": "Abstract Cyberpunk Grid Matrix Loop, Glowing Neon Motion Graphics",
  "keywords": "cyberpunk, hud, neon, portal, technology, loop, abstract, virtual reality, sci-fi"
}

Do not wrap your response in markdown code blocks like \`\`\`json. Return ONLY the raw JSON string.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: systemPrompt,
                },
              ],
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      return NextResponse.json(
        { error: `Gemini API returned error: ${errorText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      return NextResponse.json(
        { error: "No response text generated by Gemini." },
        { status: 500 }
      );
    }

    // Clean up any markdown helper wrappers if the LLM returned it
    let cleanText = generatedText.trim();
    if (cleanText.startsWith("```")) {
      cleanText = cleanText.replace(/^```json\s*/i, "").replace(/```$/, "").trim();
    }

    const result = JSON.parse(cleanText);
    return NextResponse.json(result);
  } catch (error: any) {
    console.error("Error in metadata generation route:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate metadata." },
      { status: 500 }
    );
  }
}
